Add i18n
jguitar/hq-tas-react pull request #12
Opened 2018-04-24 15:53 UTC by javier-galindo

2018-04-24 16:09 UTC, jguitar commented on src/assets/i18n/en.json
> +    "workplace": "Puesto de trabajo",
Workplace

2018-04-24 16:09 UTC, jguitar commented on src/assets/i18n/en.json
> +    "unassigned": "Sin puesto asignado",
Unassigned

2018-04-24 16:09 UTC, jguitar commented on src/assets/i18n/en.json
> +    "overoccupation": "Sobreocupacion"
Overoccupation

2018-04-24 16:10 UTC, jguitar commented on src/assets/i18n/es.json
> +    "unassigned": "Without workplace",
Sin puesto asignado

2018-04-24 16:11 UTC, jguitar commented on src/assets/i18n/es.json
> +    "overoccupation": "Overoccupation"
Sobreocupación

2018-04-24 16:11 UTC, jguitar requested changes
Creo que has hecho un mix raro entre idiomas jeje.
Revísalo

2018-04-25 06:52 UTC, javier-galindo commented
Changes applied!

2018-04-25 07:18 UTC, jguitar approved these changes

2018-04-25 07:18 UTC, merged